### ISSUE TITLE
pepc.standalone is unusable

### ISSUE THREAD

**Issue by kin-cho** [intel/pepc#1]
_pepc.standalone_ created via [Standalone version](https://github.com/intel/pepc#standalone-version) is not working:

```
bash-4.4# ./pepc.standalone
  File "./pepc.standalone", line 2
    PK^C^D
      ^
SyntaxError: invalid syntax
bash-4.4# hexdump -C -n 100 pepc.standalone
00000000  23 21 2f 75 73 72 2f 62  69 6e 2f 70 79 74 68 6f  |#!/usr/bin/pytho|
00000010  6e 33 0a 50 4b 03 04 0a  00 00 00 00 00 00 2e 88  |n3.PK...........|
00000020  54 00 00 00 00 00 00 00  00 00 00 00 00 08 00 09  |T...............|
00000030  00 2e 67 69 74 68 75 62  2f 55 54 05 00 01 00 2f  |..github/UT..../|
00000040  50 62 50 4b 03 04 0a 00  00 00 08 00 00 2e 88 54  |PbPK...........T|
00000050  b0 3d b6 d9 46 00 00 00  47 00 00 00 12 00 09 00  |.=..F...G.......|
00000060  2e 67 69 74                                       |.git|
00000064
bash-4.4#

```

**Comment by dedekind** [comment]
Humm, interesting,  never seen this. The standalone version is basically a zip archive, prepanded with the shebang. I need to research how to even debug this. Would you share more details about your environment, may be I can reproduce this? In my Fedora environment it works fine.

**Comment by kin-cho** [comment]
I'm running Oracle Linux 8 with 5.18 kernel.
Is the zip archive a [zipapp](https://docs.python.org/3/library/zipapp.html)?

**Comment by dedekind** [comment]
No, just like you can see in the instruction:

echo '#!/usr/bin/python3' > pepc.standalone
git archive --format zip HEAD >> pepc.standalone
chmod ug+x pepc.standalone

So basically whatever 'git archive' chooses.  Here is what I have:

$  git archive --format zip HEAD -o pepc.zip
$ file pepc.zip
pepc.zip: Zip archive data, at least v1.0 to extract, compression method=store

**Comment by dedekind** [comment]
@kin-cho to be frank I am not sure how to debug this. Could you try if this will work for you.

1. Check that you have python, where it is ? I assume it is in /usr/bin/python3. Here is what I got:

$ /usr/bin/python3 --version
Python 3.10.3

2. Let's try to avoid using 'git archive' and use zip directly.

cd pepc
git clean -f -d
zip -r pepc.zip *
echo '#!/usr/bin/python3' | cat - pepc.zip > pepc.standalone
python3 pepc.standalone -h

Works for me this way too.
May be you could play with zipapp too? Thanks!

**Comment by kin-cho** [comment]
@dedekind with your 2. above, ./pepc.standalone does run for me, thanks.
However, pepc commands aren't working.

bash-4.4# python3 -V
Python 3.8.8
bash-4.4# ./pepc.standalone pstates
pepc: error: please, run 'pepc -h' for help
bash-4.4# ./pepc.standalone cstates
pepc: error: please, run 'pepc -h' for help
bash-4.4# ./pepc.standalone --version
1.3.3
bash-4.4# ./pepc.standalone -h
usage: pepc [-h] [-q] [-d] [--version] [-H HOSTNAME] [-U USERNAME] [-K PRIVKEY]
            [-T TIMEOUT] [--force-color]
            ...
pepc - Power, Energy, and Performance Configuration tool for Linux.
optional arguments:
  -h                    Show this help message and exit.
  -q                    Be quiet.
  -d                    Print debugging information.
  --version             Print version and exit.
  -H HOSTNAME, --host HOSTNAME
                        Name of the host to run the command on.
  -U USERNAME, --username USERNAME
                        Name of the user to use for logging into the remote host
                        over SSH. The default user name is 'root'.
  -K PRIVKEY, --priv-key PRIVKEY
                        Path to the private SSH key that should be used for
                        logging into the remote host. By default the key is
                        automatically found from standard paths like '~/.ssh'.
  -T TIMEOUT, --timeout TIMEOUT
                        SSH connect timeout in seconds, default is 8.
  --force-color         Force coloring of the text output.
commands:
    cpu-hotplug         CPU online/offline commands.
    cstates             CPU C-state commands.
    pstates             P-state commands.
    aspm                PCI ASPM commands.
bash-4.4# hexdump -C -n 100 pepc.standalone
00000000  23 21 2f 75 73 72 2f 62  69 6e 2f 70 79 74 68 6f  |#!/usr/bin/pytho|
00000010  6e 33 0a 50 4b 03 04 0a  00 00 00 00 00 c4 5e 9c  |n3.PK.........^.|
00000020  54 00 00 00 00 00 00 00  00 00 00 00 00 07 00 1c  |T...............|
00000030  00 64 65 62 69 61 6e 2f  55 54 09 00 03 d0 e2 6a  |.debian/UT.....j|
00000040  62 79 1b 6c 62 75 78 0b  00 01 04 e8 03 00 00 04  |by.lbux.........|
00000050  e8 03 00 00 50 4b 03 04  0a 00 00 00 00 00 c4 5e  |....PK.........^|
00000060  9c 54 00 00                                       |.T..|
00000064
bash-4.4#

**Comment by dedekind** [comment]
To me it looks like the commands do work fine.

'pepc.standalone -h' gave you the help text, as requested.

**Comment by dedekind** [comment]
@kin-cho  we've released a bug-fix version where the error message is improved and gives a hint that it expects more subcommands, so should be more clear. Basically 'pepc cstates' requires more sub-commands, like 'pepc cstates info' or 'pepc cstates config'.

**Comment by kin-cho** [comment]
@dedekind thanks, 'pepc cstates info' works for me.
